"""Initial Migration

Revision ID: 75588be29669
Revises: f2ddb2c6476b
Create Date: 2020-05-03 15:49:34.607446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75588be29669'
down_revision = 'f2ddb2c6476b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
